# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLiveness():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_liveness(self):
    # Test name: liveness
    # Step # | name | target | value | comment 
    # 1 | open | / |  | 
    self.driver.get("https://mtchoun-mouh.mongulu.cm/")
    # 2 | setWindowSize | 976x1016 |  | 
    self.driver.set_window_size(976, 1016)
    # 3 | click | id=name-input |  | 
    self.driver.find_element(By.ID, "name-input").click()
    # 4 | type | id=name-input | JORDANE TSAFACK  | 
    self.driver.find_element(By.ID, "name-input").send_keys("JORDANE TSAFACK ")
    # 5 | type | id=email-input | jordanetsafack@yahoo.fr | 
    self.driver.find_element(By.ID, "email-input").send_keys("jordanetsafack@yahoo.fr")
    # 6 | click | css=.btn-primary |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    # 7 | click | css=.col-4 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-4").click()
  


